var temp1 = 23;
console.log("Number 1 : " + temp1);
var temp2 = 56;
console.log("Number 2 : " + temp2);
var pr = temp1 * temp2;
console.log("Product : " + pr);
var sum = temp1 + temp2;
console.log("Sum : " + sum);
var sub = temp2 - temp1;
console.log("num2 - num1 : " + sub);
var dev = temp2 / temp1;
console.log("Devisision(num2/num1) : " + dev);
